<?php

return [
    ['id' => 1,  'name' => 'Pasta', 'is_available' => true, 'quantity' => 1],
    ['id' => 2,  'name' => 'Pomodoro', 'is_available' => true, 'quantity' => 1],
    ['id' => 3,  'name' => 'Pomodorini', 'is_available' => true, 'quantity' => 1],
    ['id' => 4,  'name' => 'Concentrato di pomodoro', 'is_available' => true, 'quantity' => 1],
    ['id' => 5,  'name' => 'Salsa di pomodoro', 'is_available' => true, 'quantity' => 1],
    ['id' => 6,  'name' => 'Uova', 'is_available' => true, 'quantity' => 1],
    ['id' => 7,  'name' => 'Halloumi', 'is_available' => true, 'quantity' => 1],
    ['id' => 8,  'name' => 'Feta', 'is_available' => true, 'quantity' => 1],
    ['id' => 9,  'name' => 'Prezzemolo', 'is_available' => true, 'quantity' => 1],
    ['id' => 10, 'name' => 'Basilico', 'is_available' => true, 'quantity' => 1],
    ['id' => 11, 'name' => 'Origano', 'is_available' => true, 'quantity' => 1],
    ['id' => 12, 'name' => 'Aglio', 'is_available' => true, 'quantity' => 1],
    ['id' => 13, 'name' => 'Cipolla bianca', 'is_available' => true, 'quantity' => 1],
    ['id' => 14, 'name' => 'Cipolla rossa', 'is_available' => true, 'quantity' => 1],
    ['id' => 15, 'name' => 'Mozzarella', 'is_available' => true, 'quantity' => 1],
    ['id' => 16, 'name' => 'Pasta brisèe', 'is_available' => true, 'quantity' => 1],
    ['id' => 17, 'name' => 'Pasta sfoglia', 'is_available' => true, 'quantity' => 1],
    ['id' => 18, 'name' => 'Zucchine', 'is_available' => true, 'quantity' => 1],
    ['id' => 19, 'name' => 'Carote', 'is_available' => true, 'quantity' => 1],
    ['id' => 20, 'name' => 'Melanzane', 'is_available' => true, 'quantity' => 1],
    ['id' => 21, 'name' => 'Porri', 'is_available' => true, 'quantity' => 1],
    ['id' => 22, 'name' => 'Funghi', 'is_available' => true, 'quantity' => 1],
    ['id' => 23, 'name' => 'Limoni', 'is_available' => true, 'quantity' => 1],
    ['id' => 24, 'name' => 'Zucca delica', 'is_available' => true, 'quantity' => 1],
    ['id' => 25, 'name' => 'Broccoli', 'is_available' => true, 'quantity' => 1],
    ['id' => 26, 'name' => 'Cavolo romano', 'is_available' => true, 'quantity' => 1],
    ['id' => 27, 'name' => 'Finoccchi', 'is_available' => true, 'quantity' => 1],
    ['id' => 28, 'name' => 'Spinaci', 'is_available' => true, 'quantity' => 1],
    ['id' => 29, 'name' => 'Ceci', 'is_available' => true, 'quantity' => 1],
    ['id' => 30, 'name' => 'Fagioli borlotti', 'is_available' => true, 'quantity' => 1],
    ['id' => 31, 'name' => 'Fagioli spagna', 'is_available' => true, 'quantity' => 1],
    ['id' => 32, 'name' => 'Mais', 'is_available' => true, 'quantity' => 1],
    ['id' => 33, 'name' => 'Merluzzo', 'is_available' => true, 'quantity' => 1],
    ['id' => 34, 'name' => 'Nasello', 'is_available' => true, 'quantity' => 1],
    ['id' => 35, 'name' => 'Vongole', 'is_available' => true, 'quantity' => 1],
    ['id' => 36, 'name' => 'Salsa di soia', 'is_available' => true, 'quantity' => 1],
    ['id' => 37, 'name' => 'Ricotta', 'is_available' => true, 'quantity' => 1],
    ['id' => 38, 'name' => 'Sale', 'is_available' => true, 'quantity' => 1],
    ['id' => 39, 'name' => 'Pepe nero', 'is_available' => true, 'quantity' => 1],
    ['id' => 40, 'name' => 'Pepe bianco', 'is_available' => true, 'quantity' => 1],
    ['id' => 41, 'name' => 'Cumino', 'is_available' => true, 'quantity' => 1],
    ['id' => 42, 'name' => 'Maggiorana', 'is_available' => true, 'quantity' => 1],
    ['id' => 43, 'name' => 'Menta', 'is_available' => true, 'quantity' => 1],
    ['id' => 44, 'name' => 'Peperonicino', 'is_available' => true, 'quantity' => 1],
    ['id' => 45, 'name' => 'Paprika affumicata', 'is_available' => true, 'quantity' => 1],
    ['id' => 46, 'name' => 'Paprika dolce', 'is_available' => true, 'quantity' => 1],
    ['id' => 47, 'name' => 'Peperoni rossi', 'is_available' => true, 'quantity' => 1],
    ['id' => 48, 'name' => 'Peperoni gialli', 'is_available' => true, 'quantity' => 1],
    ['id' => 49, 'name' => 'Pollo', 'is_available' => true, 'quantity' => 1],
    ['id' => 50, 'name' => 'Salsiccia', 'is_available' => true, 'quantity' => 1],
    ['id' => 51, 'name' => 'Parmigiano', 'is_available' => true, 'quantity' => 1],
    ['id' => 52, 'name' => 'Fontina', 'is_available' => true, 'quantity' => 1],
    ['id' => 53, 'name' => 'Tomini', 'is_available' => true, 'quantity' => 1],
    ['id' => 54, 'name' => 'Brie', 'is_available' => true, 'quantity' => 1],
    ['id' => 55, 'name' => 'Gorgonzola', 'is_available' => true, 'quantity' => 1],
    ['id' => 56, 'name' => 'Philadelphia', 'is_available' => true, 'quantity' => 1],
    ['id' => 57, 'name' => 'Robiola', 'is_available' => true, 'quantity' => 1],
    ['id' => 58, 'name' => 'Marmellata', 'is_available' => true, 'quantity' => 1],
    ['id' => 59, 'name' => 'Mele', 'is_available' => true, 'quantity' => 1],
    ['id' => 60, 'name' => 'Pere', 'is_available' => true, 'quantity' => 1],
    ['id' => 61, 'name' => 'Albicocche', 'is_available' => true, 'quantity' => 1],
    ['id' => 62, 'name' => 'Pesche noci', 'is_available' => true, 'quantity' => 1],
    ['id' => 63, 'name' => 'Pesche tabacchiere', 'is_available' => true, 'quantity' => 1],
    ['id' => 64, 'name' => 'Fragole', 'is_available' => true, 'quantity' => 1],
    ['id' => 65, 'name' => 'Lamponi', 'is_available' => true, 'quantity' => 1],
    ['id' => 66, 'name' => 'Mirtilli', 'is_available' => true, 'quantity' => 1],
    ['id' => 67, 'name' => 'Yoghurt bianco', 'is_available' => true, 'quantity' => 1],
    ['id' => 68, 'name' => 'Mascarpone', 'is_available' => true, 'quantity' => 1],
    ['id' => 69, 'name' => 'Panna da cucina', 'is_available' => true, 'quantity' => 1],
    ['id' => 70, 'name' => 'Panna da montare', 'is_available' => true, 'quantity' => 1],
    ['id' => 71, 'name' => 'Sesamo', 'is_available' => true, 'quantity' => 1],
    ['id' => 72, 'name' => 'Nocciole', 'is_available' => true, 'quantity' => 1],
];
