<?php

return [
    ['id' => 1,  'name' => 'Pasta', 'slug' => 'pasta', 'is_available' => true, 'quantity' => 1],
    ['id' => 2,  'name' => 'Pomodoro', 'slug' => 'pomodoro', 'is_available' => true, 'quantity' => 1],
    ['id' => 3,  'name' => 'Pomodorini', 'slug' => 'pomodorini', 'is_available' => true, 'quantity' => 1],
    ['id' => 4,  'name' => 'Concentrato di pomodoro', 'slug' => 'concentrato-di-pomodoro', 'is_available' => true, 'quantity' => 1],
    ['id' => 5,  'name' => 'Salsa di pomodoro', 'slug' => 'salsa-di-pomodoro', 'is_available' => true, 'quantity' => 1],
    ['id' => 6,  'name' => 'Uova', 'slug' => 'uova', 'is_available' => true, 'quantity' => 1],
    ['id' => 7,  'name' => 'Halloumi', 'slug' => 'halloumi', 'is_available' => true, 'quantity' => 1],
    ['id' => 8,  'name' => 'Feta', 'slug' => 'feta', 'is_available' => true, 'quantity' => 1],
    ['id' => 9,  'name' => 'Prezzemolo', 'slug' => 'prezzemolo', 'is_available' => true, 'quantity' => 1],
    ['id' => 10, 'name' => 'Basilico', 'slug' => 'basilico', 'is_available' => true, 'quantity' => 1],
    ['id' => 11, 'name' => 'Origano', 'slug' => 'origano', 'is_available' => true, 'quantity' => 1],
    ['id' => 12, 'name' => 'Aglio', 'slug' => 'aglio', 'is_available' => true, 'quantity' => 1],
    ['id' => 13, 'name' => 'Cipolla bianca', 'slug' => 'cipolla-bianca', 'is_available' => true, 'quantity' => 1],
    ['id' => 14, 'name' => 'Cipolla rossa', 'slug' => 'cipolla-rossa', 'is_available' => true, 'quantity' => 1],
    ['id' => 15, 'name' => 'Mozzarella', 'slug' => 'mozzarella', 'is_available' => true, 'quantity' => 1],
    ['id' => 16, 'name' => 'Pasta brisèe', 'slug' => 'pasta-brisee', 'is_available' => true, 'quantity' => 1],
    ['id' => 17, 'name' => 'Pasta sfoglia', 'slug' => 'pasta-sfoglia', 'is_available' => true, 'quantity' => 1],
    ['id' => 18, 'name' => 'Zucchine', 'slug' => 'zucchine', 'is_available' => true, 'quantity' => 1],
    ['id' => 19, 'name' => 'Carote', 'slug' => 'carote', 'is_available' => true, 'quantity' => 1],
    ['id' => 20, 'name' => 'Melanzane', 'slug' => 'melanzane', 'is_available' => true, 'quantity' => 1],
    ['id' => 21, 'name' => 'Porri', 'slug' => 'porri', 'is_available' => true, 'quantity' => 1],
    ['id' => 22, 'name' => 'Funghi', 'slug' => 'funghi', 'is_available' => true, 'quantity' => 1],
    ['id' => 23, 'name' => 'Limoni', 'slug' => 'limoni', 'is_available' => true, 'quantity' => 1],
    ['id' => 24, 'name' => 'Zucca delica', 'slug' => 'zucca-delica', 'is_available' => true, 'quantity' => 1],
    ['id' => 25, 'name' => 'Broccoli', 'slug' => 'broccoli', 'is_available' => true, 'quantity' => 1],
    ['id' => 26, 'name' => 'Cavolo romano', 'slug' => 'cavolo-romano', 'is_available' => true, 'quantity' => 1],
    ['id' => 27, 'name' => 'Finoccchi', 'slug' => 'finoccchi', 'is_available' => true, 'quantity' => 1],
    ['id' => 28, 'name' => 'Spinaci', 'slug' => 'spinaci', 'is_available' => true, 'quantity' => 1],
    ['id' => 29, 'name' => 'Ceci', 'slug' => 'ceci', 'is_available' => true, 'quantity' => 1],
    ['id' => 30, 'name' => 'Fagioli borlotti', 'slug' => 'fagioli-borlotti', 'is_available' => true, 'quantity' => 1],
    ['id' => 31, 'name' => 'Fagioli spagna', 'slug' => 'fagioli-spagna', 'is_available' => true, 'quantity' => 1],
    ['id' => 32, 'name' => 'Mais', 'slug' => 'mais', 'is_available' => true, 'quantity' => 1],
    ['id' => 33, 'name' => 'Merluzzo', 'slug' => 'merluzzo', 'is_available' => true, 'quantity' => 1],
    ['id' => 34, 'name' => 'Nasello', 'slug' => 'nasello', 'is_available' => true, 'quantity' => 1],
    ['id' => 35, 'name' => 'Vongole', 'slug' => 'vongole', 'is_available' => true, 'quantity' => 1],
    ['id' => 36, 'name' => 'Salsa di soia', 'slug' => 'salsa-di-soia', 'is_available' => true, 'quantity' => 1],
    ['id' => 37, 'name' => 'Ricotta', 'slug' => 'ricotta', 'is_available' => true, 'quantity' => 1],
    ['id' => 38, 'name' => 'Sale', 'slug' => 'sale', 'is_available' => true, 'quantity' => 1],
    ['id' => 39, 'name' => 'Pepe nero', 'slug' => 'pepe-nero', 'is_available' => true, 'quantity' => 1],
    ['id' => 40, 'name' => 'Pepe bianco', 'slug' => 'pepe-bianco', 'is_available' => true, 'quantity' => 1],
    ['id' => 41, 'name' => 'Cumino', 'slug' => 'cumino', 'is_available' => true, 'quantity' => 1],
    ['id' => 42, 'name' => 'Maggiorana', 'slug' => 'maggiorana', 'is_available' => true, 'quantity' => 1],
    ['id' => 43, 'name' => 'Menta', 'slug' => 'menta', 'is_available' => true, 'quantity' => 1],
    ['id' => 44, 'name' => 'Peperonicino', 'slug' => 'peperonicino', 'is_available' => true, 'quantity' => 1],
    ['id' => 45, 'name' => 'Paprika affumicata', 'slug' => 'paprika-affumicata', 'is_available' => true, 'quantity' => 1],
    ['id' => 46, 'name' => 'Paprika dolce', 'slug' => 'paprika-dolce', 'is_available' => true, 'quantity' => 1],
    ['id' => 47, 'name' => 'Peperoni rossi', 'slug' => 'peperoni-rossi', 'is_available' => true, 'quantity' => 1],
    ['id' => 48, 'name' => 'Peperoni gialli', 'slug' => 'peperoni-gialli', 'is_available' => true, 'quantity' => 1],
    ['id' => 49, 'name' => 'Pollo', 'slug' => 'pollo', 'is_available' => true, 'quantity' => 1],
    ['id' => 50, 'name' => 'Salsiccia', 'slug' => 'salsiccia', 'is_available' => true, 'quantity' => 1],
    ['id' => 51, 'name' => 'Parmigiano', 'slug' => 'parmigiano', 'is_available' => true, 'quantity' => 1],
    ['id' => 52, 'name' => 'Fontina', 'slug' => 'fontina', 'is_available' => true, 'quantity' => 1],
    ['id' => 53, 'name' => 'Tomini', 'slug' => 'tomini', 'is_available' => true, 'quantity' => 1],
    ['id' => 54, 'name' => 'Brie', 'slug' => 'brie', 'is_available' => true, 'quantity' => 1],
    ['id' => 55, 'name' => 'Gorgonzola', 'slug' => 'gorgonzola', 'is_available' => true, 'quantity' => 1],
    ['id' => 56, 'name' => 'Philadelphia', 'slug' => 'philadelphia', 'is_available' => true, 'quantity' => 1],
    ['id' => 57, 'name' => 'Robiola', 'slug' => 'robiola', 'is_available' => true, 'quantity' => 1],
    ['id' => 58, 'name' => 'Marmellata', 'slug' => 'marmellata', 'is_available' => true, 'quantity' => 1],
    ['id' => 59, 'name' => 'Mele', 'slug' => 'mele', 'is_available' => true, 'quantity' => 1],
    ['id' => 60, 'name' => 'Pere', 'slug' => 'pere', 'is_available' => true, 'quantity' => 1],
    ['id' => 61, 'name' => 'Albicocche', 'slug' => 'albicocche', 'is_available' => true, 'quantity' => 1],
    ['id' => 62, 'name' => 'Pesche noci', 'slug' => 'pesche-noci', 'is_available' => true, 'quantity' => 1],
    ['id' => 63, 'name' => 'Pesche tabacchiere', 'slug' => 'pesche-tabacchiere', 'is_available' => true, 'quantity' => 1],
    ['id' => 64, 'name' => 'Fragole', 'slug' => 'fragole', 'is_available' => true, 'quantity' => 1],
    ['id' => 65, 'name' => 'Lamponi', 'slug' => 'lamponi', 'is_available' => true, 'quantity' => 1],
    ['id' => 66, 'name' => 'Mirtilli', 'slug' => 'mirtilli', 'is_available' => true, 'quantity' => 1],
    ['id' => 67, 'name' => 'Yoghurt bianco', 'slug' => 'yoghurt-bianco', 'is_available' => true, 'quantity' => 1],
    ['id' => 68, 'name' => 'Mascarpone', 'slug' => 'mascarpone', 'is_available' => true, 'quantity' => 1],
    ['id' => 69, 'name' => 'Panna da cucina', 'slug' => 'panna-da-cucina', 'is_available' => true, 'quantity' => 1],
    ['id' => 70, 'name' => 'Panna da montare', 'slug' => 'panna-da-montare', 'is_available' => true, 'quantity' => 1],
    ['id' => 71, 'name' => 'Sesamo', 'slug' => 'sesamo', 'is_available' => true, 'quantity' => 1],
    ['id' => 72, 'name' => 'Nocciole', 'slug' => 'nocciole', 'is_available' => true, 'quantity' => 1],
    ['id' => 73, 'name' => 'Riso Carnaroli', 'slug' => 'riso-carnaroli', 'is_available' => true, 'quantity' => 1]
];
